### ISSUE TITLE
Abbreviation for degree Celsius 

### ISSUE THREAD

**Issue by fluffy** [core-wg/senml-spec#2]
Should it be degC or Cel or something else

**Comment by joseangeljimenez** [comment]
My rationale for switching to "°C" for Celsius degree,

- The SI base unit for temperature is the Kelvin degree, simply abbreviated "K".
- The Celsius degree is a SI derived unit. The standard way to typeset the unit is "°C" (degree sign + latin capital letter C).
- The NIST also recommends "°C".
- Beware that there is a Unicode point for degree Celsius, however, it is only for historial reasons. The Unicode standard indicates: 'In normal use, it is better to represent degrees Celsius "°C" with a sequence of U+00B0 ° degree sign + U+0043 C latin capital letter c'.

If you prefer something simpler, a single "C" (without °) has been also extensively used in science and academia, historically.

References
https://www.nist.gov/pml/weights-and-measures/writing-metric-units
https://en.wikipedia.org/wiki/Celsius#Name_and_symbol_typesetting
https://en.wikipedia.org/wiki/SI_derived_unit

**Comment by cabo** [comment]
Actually, it should be °C (DEGREE SIGN Celsius), not ºC (MASCULINE ORDINAL INDICATOR Celsius).
You got this right once (and in the choice of U+00B0) and wrong three times in your message.

Apart from this nice demonstration of the difficulty of finding the right character, there isn’t really that much of a hard argument against °C — it is the same number of bytes (C2 B0 43) as “Cel” (43 65 6c).  Except that it contains a beyond-ASCII character, which we studiously have avoided in SenML.

“C" can’t be really used because it is the symbol for coulomb, the unit of electrical charge.

I believe “Cel” continues to stand as the smaller evil.

Grüße, Carsten

**Comment by joseangeljimenez** [comment]
You are absolutely right that C is the SI unit for electric charge. It's a strong argument against.

However, I don't see how can "Cel" compete with "°C", being the latter the standard way of typesetting the unit, according to the SI and also recommended by NIST. We don't need to reinvent the wheel here, simply follow the standard.

Last argument, as an open question for the group: Would you ever design a wall thermometer showing Celsius degrees as "Cel"? Really?
